language : node_js

node_js:
 - "10"

cache:
  directories:
    - "node_modules"

branches:
  only:
    - develop

install:
  - npm ci
  - npm run generate

script:
  - npm run lint
  # - npm run test

deploy:
  provider: pages
  cleanup: true
  token: $PES_ACCESS_TOKEN
  target_branch: master
  local_dir: dist
  on:
    branch: develop

# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $PES_ACCESS_TOKEN
#   target-branch: master
#   local-dir: dist
#   on:
#     branch: develop
